export const englishText = {
    addToCart: 'Add To Cart',
    Our: "Our",
    Product: "Product",
    Profile: "Profile",
    ChangePhoto: "Change Photo",
    Orders: "Orders",
    Password: "Password",
    SignOut: "Sign-Out",
    Items: "Items",  // New translation for "items"
    Checkout: "Checkout",
    Cart: "Cart",
    Conform: "Conform",
    Order: "Order",
    Subtotal: "Subtotal",
    Tax: "Tax",
    ShippingCharge: "Shipping Charge",
    TotalAmount: "Total Amount",
    Payment: "Payment",
};

export const hindiText = {
    addToCart: 'कार्ट में डालें',
    Our: "हमारा",
    Product: "प्रोडक्ट",
    Profile: "प्रोफ़ाइल",
    ChangePhoto: "फोटो बदलें",
    Orders: "ऑर्डर",
    Password: "पासवर्ड",
    SignOut: "साइन आउट",
    Items: "वस्तुएँ",
    Checkout: "चेकआउट",
    Cart: "कार्ट",
    Conform: "पुष्टि करें",
    Order: "ऑर्डर",
    Subtotal: "कुल",
    Tax: "टैक्स",
    ShippingCharge: "शिपिंग शुल्क",
    TotalAmount: "कुल रकम",
    Payment: "भुगतान",
};
export const gujaratiText = {
    addToCart: 'કાર્ટમાં ઉમેરો',
    Our: 'અમારો',
    Product: 'ઉત્પાદન',
    Profile: 'પ્રોફાઇલ',
    ChangePhoto: 'ફોટો બદલો',
    Orders: 'ઓર્ડર',
    Password: 'પાસવર્ડ',
    SignOut: 'સાઇન-આઉટ કરો',
    Items: 'વસ્તુઓ',
    Checkout: 'ચેકઆઉટ કરો',
    Cart: 'કાર્ટ',
    Conform: 'સાચાવો',
    Order: 'ઓર્ડર',
    Subtotal: 'બાકી કુલ',
    Tax: 'કર',
    ShippingCharge: 'શિપિંગ ચાર્જ',
    TotalAmount: 'કુલ રકમ',
    Payment: 'પેમેન્ટ',
};